### PR TITLE
Add dependency overview to README.md

### PR DESCRIPTION
**Pull request by raphinesse**
### Motivation and Context

Provide a high-level overview about the package relationships in a prominent place.

### Description

Added a sketchy dependency graph of a subset of Cordova. Including a link to the Graphviz source code, so the graph can be adjusted if necessary.

### CODE REVIEW

**Review by janpio — APPROVED** [review]

**Review by NiklasMerz — COMMENTED** [review]
Looks good to me. Nice tool! Should we add the image file to repo in case the URL goes down?

**Comment by raphinesse** [comment]
> Looks good to me. Nice tool! Should we add the image file to repo in case the URL goes down?

I personally wouldn't bother as the source code for the diagram is [saved in a gist](https://gist.github.com/raphinesse/a6f28acb2281b782d9fb5ef486834deb) and the image (sans sketchiness) can be recreated with regular `graphviz`.

**Review by NiklasMerz — APPROVED** [review]
> I personally wouldn't bother as the source code for the diagram is saved in a gist and the image (sans sketchiness) can be recreated with regular graphviz. Plus, it would be one more place to update if the graph were to change.

Totally makes sense :+1:

**Comment by raphinesse** [comment]
> Looks good to me. Nice tool! Should we add the image file to repo in case the URL goes down?

Possible drawback of NOT adding the image to the repo: I can change it to anything I want by editing the code in my gist. :grin:

**Comment by brodybits** [comment]
Any way we could add the code, as a comment for example?

**Comment by raphinesse** [comment]
> > Looks good to me. Nice tool! Should we add the image file to repo in case the URL goes down?
> 
> Possible drawback of NOT adding the image to the repo: I can change it to anything I want by editing the code in my gist.

Sorry, that's not true. The image references a specific version of the gist.


> Any way we could add the code, as a comment for example?

I thought about that, but the code would be duplicated between the comment and the gist, having a negative impact on maintainability. An alternative (non-sketchy) approach would be to use that glitch service that I used for prior graphs. Its links contain the graph code as an url parameter: https://graphviz2.glitch.me/?graph=digraph+%22Cordova+Dependencies%22+%7B%0Acli+-%3E+%7Blib%2C+create%2C+common%7D%3B%0Aplugman+-%3E+lib%3B%0Alib+-%3E+%7Bfetch%2C+serve%2C+common%7D%3B%0Alib+-%3E+platforms+%5Bstyle%3Ddotted%5D%3B%0Acreate+-%3E+%7Bfetch%2C+%22app-hello-world%22%2C+common%7D%3B%0Afetch+-%3E+common%3B%0A%0Aplatforms+%5Bshape%3Drecord+label%3D%22%7BPlatforms%7C%7B%3Call%3E*%7C%3Capple%3Eios%2C+osx%7C%3Cwww%3Ebrowser%7D%7D%22%5D%3B%0Aplatforms%3Aapple+-%3E+%22node-xcode%22%3B%0Aplatforms%3Awww+-%3E+serve%3B%0Aplatforms%3Aall+-%3E+common%3B%0Aplatforms%3Aall+-%3E+js+%5Bstyle%3Ddotted%5D%3B%0A%7D%0A

**Review by erisu — APPROVED** [review]

**Pull request merged**
